const fs = require('fs');

const existingGames = JSON.parse(fs.readFileSync('./src/games.json', 'utf-8'));

const newGamesData = [
  ["10 Minutes Till Dawn", "cl10minutestildawn.html"],
  ["12 Mini Battles", "cl12minibattles.html"],
  ["2048 Cupcakes", "cl2048cupcakes.html"],
  ["2-3-4 Player Games", "cl234playergame.html"],
  ["20 Small Mazes", "cl20smallmazes.html"],
  ["2Doom", "cl2doomy.html"],
  ["2D Shooting", "cl2Dshooting.html"],
  ["3Dash", "cl3dashy.html"],
  ["3Dash Editor", "cl3dash.html"],
  ["3D Pinball Space Cadet", "cl3dpinballspacecadet.html"],
  ["4th And Goal", "cl4thandgoal.html"],
  ["500 Caliber Contractz", "cl500calibercontractz.html"],
  ["8 Ball Classic", "cl8ballclassic.html"],
  ["9007199254740992", "cl9007199254740992.html"],
  ["99 Balls", "cl99balls.html"],
  ["99 Nights In The Forest", "cl99nightsitf.html"],
  ["A Dance of Fire and Ice", "clADOFAI.html"],
  ["A Date With Death", "cladatewithdeath.html"],
  ["A Day In The Office", "cladayintheoffice.html"],
  ["Advent Neon", "cladventneon.html"],
  ["Adventure Capitalist", "clAdventureCapatalist.html"],
  ["Ahoy Survival", "clahoysurvival.html"],
  ["Airline Tycoon Idle", "clairlinetycoonidle.html"],
  ["Agar.io Lite", "clagariolite.html"],
  ["Ages of Conflict", "clagesofconflict.html"],
  ["Alien Sky Invasion", "clalienskyinvasion.html"],
  ["Allocation", "clallocation.html"],
  ["Amazing Strange Rope Police", "clstreangeropepolice.html"],
  ["Amidst The Sky", "clamidstthesky.html"],
  ["Amorphous +", "clamorphous.html"],
  ["Ancient Sins", "clancientsins.html"],
  ["Angry Birds Online", "clangrybirdsonline.html"],
  ["Angry Birds Showdown", "clangrybirdsshowdown.html"],
  ["Antimatter Dimensions", "clantimatterdimensions.html"],
  ["Ant Art Tycoon", "clantarttycoon.html"],
  ["Apes vs. Helium", "clapesvshelium.html"],
  ["Aquapark.io", "claquaparkio.html"],
  ["Archery World Tour", "clarcheryworldtour.html"],
  ["Arsonate", "clarsonate.html"],
  ["Are We There Yet", "clarewethereyet.html"],
  ["Arthur's Nightmare", "clarthursnightmare.html"],
  ["Ascent", "clascent.html"],
  ["Assessment Examination", "classesmentexaminationque.html"],
  ["As Duty Demands", "clasdutydemands.html"],
  ["Asteroids", "clasteroidsALT.html"],
  ["A Small World Cup", "clasmallworldcup.html"],
  ["Aviamasters", "claviamastersbuggy.html"],
  ["Babel Tower", "clbabeltower.html"],
  ["Baby Chicco Adventure", "clbabychiccoadventure.html"],
  ["Baby Sniper In Vietnam", "clbabysniperinvietnam.html"],
  ["Backrooms", "clbackrooms.html"],
  ["Backrooms 2D", "clbackrooms2D.html"],
  ["Bacon May Die", "clbaconmaydie.html"],
  ["Bad Bodyguards", "clbadbodyguards.html"],
  ["Bad Monday Simulator", "clbadmondaysimulator.html"],
  ["Bad Parenting", "clbadparenting.html"],
  ["Bad Piggies (LATEST)", "clbadpiggieslatest.html"],
  ["Bad Time Simulator", "clbadtimesim.html"],
  ["Baldi's Basics Remastered", "clbaldisbasicsremaster.html"],
  ["Baldi's Basics The Ultra Decompile", "clbaldidecomp.html"],
  ["Baldi's Fun New School Ultimate", "clbaldisfunnewschoolultimate.html"],
  ["Ballistic", "clballistic.html"],
  ["Balls And Bricks", "clballsandbricksgood.html"],
  ["Ball Blast", "clballblast.html"],
  ["BallZ", "clballz.html"],
  ["Banana Simulator", "clbananasimulator.html"],
  ["Bank Robbery 1", "clbankrobbery1.html"],
  ["Bank Robbery 2", "clbankrobbery2.html"],
  ["Barry Has a Secret", "clbarryhasasecret.html"],
  ["BAS", "clbas.html"],
  ["Baseball Bros", "clbaseballbros.html"],
  ["Basket Battle", "clbasketbattle.html"],
  ["Basket Bros", "clbasketbros.html"],
  ["Basket Slam Dunk 2", "clbasketslamdunk2.html"],
  ["Basketball FRVR", "clbasketballfrvr.html"],
  ["Basketball Legends 2020", "clbasketballlegends.html"],
  ["Basketball Stars", "clbasketballstars.html"],
  ["Basketball Superstars", "clbasketballsuperstars.html"],
  ["Batter Up", "clbatterup.html"],
  ["Battles", "clbattles.html"],
  ["Battle Karts", "clbattlekarts.html"],
  ["Battle Simulator", "clbattlesim.html"],
  ["Beach Boxing Simulator", "clbeachboxingsim.html"],
  ["Bearsus", "clbearsus.html"],
  ["BERGENTRUCK 201x", "clbergentruck201x.html"],
  ["BFDIA 5b", "clbfdia5b.html"],
  ["BFDI Branches", "clbfdibranches.html"],
  ["Big Flappy Tower Tiny Square", "clbigflappytowertinysquare.html"],
  ["Big Ice Tower Tiny Square", "clbigicetowertinysquare.html"],
  ["Big Neon Tower Tiny Square", "clbigneontowertinysquare.html"],
  ["Big Shot Boxing", "clbigshotboxing2.html"],
  ["Big Tower Tiny Square", "clbtts.html"],
  ["Big Tower Tiny Square 2", "clbtts2.html"],
  ["Bio Evil 4", "clbioevil4.html"],
  ["Bit Planes", "clbitplanes.html"],
  ["Blackjack", "clblackjackhhhh.html"],
  ["Blastronaut", "clblastronaut.html"],
  ["Blaze Drifter", "clblazedrifter.html"],
  ["Blightborne", "clblightborne.html"],
  ["Block Blast", "clblockblast.html"],
  ["Block Blast 2", "clblockblastv2.html"],
  ["Blockpost", "clblockpost.html"],
  ["Block the Pig", "clblockthepig.html"],
  ["Blocky Demolition Derby", "clblockydemolitionderby.html"],
  ["Blocky Snakes", "clblockysnakes.html"],
  ["Blood Tournament", "clbloodtournament.html"],
  ["Bloodmoney", "clbloodmoney.html"],
  ["Blumgi Racers", "clblumgiracers.html"],
  ["Blumgi Rocket", "clblumgirocket.html"],
  ["Bob the Robber 2", "clbobtherobber2.html"],
  ["Bob the Robber 5", "clbobtherobber5.html"],
  ["Boba Simulator", "clbobasimulator.html"],
  ["Boom Slingers", "clboomslingers.html"],
  ["Bottle Cracks", "clbottlecracks.html"],
  ["Bottle Jump 3d", "clbottlejump3d.html"],
  ["Bouncemasters", "clbouncemasters.html"],
  ["Bounce Back", "clbounceback.html"],
  ["Bouncy Basketball", "clbouncybasketball.html"],
  ["Bouncy Motors", "clbouncymotors.html"],
  ["Bounty of One", "clBountyOfOne.html"],
  ["Bowmasters", "clbowmaster.html"],
  ["Boxing Random", "clboxingrandom.html"],
  ["Brawl Simulator 3D", "clbrawlsimulator3d.html"],
  ["Brawl Stars (REMAKE)", "clbrawlstarsremake.html"],
  ["Breadskate Forever", "clbreadskate.html"],
  ["Bridge Race", "clbridgerace.html"],
  ["Brotato", "clbrotato.html"],
  ["BTD6 (scratch)", "clbloonsTD6scratch.html"],
  ["BuildNow.GG", "clbuildnowgg.html"],
  ["Build-Defend", "clbuild.html"],
  ["Bunnyland", "clbunnyland.html"],
  ["Burger and Frights", "clburgerandfrights.html"],
  ["Burrito Bison Launcha Libre", "clburritobisonlaunchalibre.html"],
  ["Buster Jam", "clBusterJam.html"],
  ["Cannon Balls 3D", "clcannonballs3d.html"],
  ["Candy Box 1", "clcandybox1.html"],
  ["Capybara Clicker", "clcapybaraclicker.html"],
  ["Car Crash 3", "clcarcrash3.html"],
  ["Car Drawing", "clcardrawing.html"],
  ["Car King Arena", "clcarkingarena.html"],
  ["Car Ramp Vs Police Chase", "clcarrampvspolicechase.html"],
  ["Call of Battle", "clcallofbattle.html"],
  ["CaptchaWare", "clcaptchaware.html"],
  ["Cartoon Network Table Tennis Ultimate Tournament", "clCartoonNetworkTableTennisUltimateTournament.html"],
  ["Castle Wars Modern", "clcastlewarsmodern.html"],
  ["Cat Mario (flash)", "clcatmario.html"],
  ["Cats Love Cake 2", "clcatslovecake2.html"],
  ["Cave Crawler", "clcavecrawler.html"],
  ["Cave Story", "clcavestory.html"],
  ["Celeste Pico", "clceleste.html"],
  ["Celeste 2", "clceleste2.html"],
  ["Cell Machine", "clcellmachine.html"],
  ["Cell to Singularity", "clCelltoSingularity.html"],
  ["Chaos Faction 2", "clchaosfaction2.html"],
  ["Cheese Chompers 3D", "clcheesechompers3d.html"],
  ["Cheese Is The Reason", "clcheeseisthereason.html"],
  ["ChickenCS", "clchickencs.html"],
  ["Cheshire In a Chatroom", "clcheshireinachatroom.html"],
  ["Chess Classic", "clchessclassic.html"],
  ["Chicken Scream", "clchickenscream.html"],
  ["Chickenwar", "clchickenwar.html"],
  ["Choppy Orc", "clchoppyorc.html"],
  ["CircloO 2", "clCircloO2.html"],
  ["Civiballs", "clciviballs.html"],
  ["Civiballs 2", "clciviballs2.html"],
  ["Clash Of Vikings", "clclashofvikings.html"],
  ["Class of '09", "clclassof09.html"],
  ["Cleanup.io", "clcleanupio.html"],
  ["Cluster Rush", "clclusterrush.html"],
  ["Coal LLC", "clcoalllcdemo.html"],
  ["Cold Pines", "clcoldpines.html"],
  ["Coffee Maker", "clcoffeemaker.html"],
  ["Colorbox Mustard", "clColorboxmustard.html"],
  ["Combo Pool", "clcombopool.html"],
  ["Command and Conquer Red Alert", "clredalert.html"],
  ["Command and Conquer Tiberian Dawn", "cltiberiandawn.html"],
  ["Cookie Clicker Mod Menu", "clcookieclickermodmenu.html"],
  ["Core Ball", "clcoreball.html"],
  ["Count Masters: Stickman Games", "clcountmastersstickmangames.html"],
  ["Counter Snipe", "clcountersnipe.html"],
  ["Crank It!", "clcrankit!.html"],
  ["Crazy Cars", "clcrazycars.html"],
  ["Crazy Cattle 3D", "clcrazycattle3d.html"],
  ["Crazy Chicken 3D", "clcrazychicken3D.html"],
  ["Crazy Crash Landing", "cldubstep.html"],
  ["Crazy Motorcycle", "clcrazymotorcycle.html"],
  ["Crazy Plane Landing", "clcrazyplanelanding.html"],
  ["Creature Card Idle", "clcreaturecardidle.html"],
  ["Crossy Road", "clcrossyroad.html"],
  ["C.S 1.6", "clcs1.6.html"],
  ["Csgo Clicker", "clcsgoclicker.html"],
  ["Customer Support", "clcustomersupport.html"],
  ["Curse of the Lich King", "clcotlk.html"],
  ["Cut the Rope: Holiday", "clcuttherope.html"],
  ["Cut the Rope: Time Travel", "clcuttherope.html"],
  ["Cyberbung Racing", "clcyberbungracing.html"],
  ["Dadish", "cldadish.html"],
  ["Dandy's World Clicker", "cldandysworldclicker.html"],
  ["Dan the Man", "cldtm.html"],
  ["Dank Tomb", "cldanktomb.html"],
  ["Dash Party", "cldashio.html"],
  ["Dash Arena", "cldasharena.html"],
  ["Dead Estate", "cldeadestate.html"],
  ["Dead Plate", "cldeadplate.html"],
  ["Dead Seat", "cldeadseat.html"],
  ["Deadly Descent", "cldeadlydescent.html"],
  ["Death Run", "cldeathrun.html"],
  ["Death Chase", "cldeathchase.html"],
  ["Deepest Sword", "cldeepestsword.html"],
  ["Deltarune", "cldeltarune.html"],
  ["Deltarune: A Different Snowgrave", "cladifferentsnowgrave.html"],
  ["Deltatraveler", "cldeltatraveler.html"],
  ["Demolition Derby Crash Racing", "cldemolitionderbycrashracing.html"],
  ["Demon Bluff", "cldemonbluff.html"],
  ["Die in the Dungeon", "cldieinthedungeon.html"],
  ["Dire Decks", "cldiredecks.html"],
  ["Doblox", "cldoblox.html"],
  ["Doors Castle", "cldoorscastle.html"],
  ["Doge Miner", "cldogeminer.html"],
  ["Doge Miner 2", "cldogeminer2.html"],
  ["Dome Romantik", "cldomeromantik.html"],
  ["Doki Doki Literature Club", "cldokidokiliteratureclub.html"],
  ["Doom But It's Half Life 2", "clhl2doom.html"],
  ["Doom Emscripten", "cldoomemscripten.html"],
  ["Doom Gallery Experience", "cldoomgallery.html"],
  ["Doomz.io", "cldoomzio.html"],
  ["Double Barrel Sniper", "cldbsniper.html"],
  ["Draw Climber", "cldrawclimber.html"],
  ["Draw the Line", "cldrawtheline.html"],
  ["DTA 6", "cldta6.html"],
  ["Dreader", "cldreader.html"],
  ["Dreadhead Parkour", "cldreadheadparkour.html"],
  ["Dr. Weed Gaster", "cldrweedgaster.html"],
  ["Drift Simulator", "cldriftsimulator.html"],
  ["Drift Hunters", "cldrifthuntersmerge.html"],
  ["Drive In Russia", "cldriverussia.html"],
  ["Drive Mad", "cldrivemady.html"],
  ["Driven Wild", "cldrivenwild.html"],
  ["Dimensional Incident", "cldimensionalincident.html"],
  ["Duck Life Space", "clducklifespace.html"],
  ["Duck Life Battle", "clducklifebattle.html"],
  ["Ducklings.io", "clducklingsio.html"],
  ["DUD", "cldud.html"],
  ["Duke Nukem 3D", "cldukenukem3d.html"],
  ["Dumb Ways to Die", "cldumbwaystodie.html"],
  ["Dungeon Deck", "cldungeondeck.html"],
  ["Dungeon Raid", "cldungeonraid.html"],
  ["Dungeons And Degenerate Gamblers", "cldungeonsanddegenerategamblers.html"],
  ["Dunk Shot", "cldunkshot.html"],
  ["Duke Nukem 2", "cldukenukem2.html"],
  ["Dusk Child", "clduskchild.html"],
  ["Dying Dreams", "cldyingdreams.html"],
  ["Eagle Ride", "cleagleride.html"],
  ["Edelweiss", "cledelweiss.html"],
  ["Edy's Car Simulator", "cledyscarsimulator.html"],
  ["Effing Hail", "cleffinghail.html"],
  ["Egg", "clegg.html"],
  ["Eggy Car", "cleggycar.html"],
  ["Elastic Face", "clelasticface.html"],
  ["Elytra Flight", "clelytraflight.html"],
  ["Enchain", "clenchain.html"],
  ["Endacopia", "clendacopia.html"],
  ["Escalating Duel", "clescalatingduel.html"],
  ["Escape School Duel", "clescapeschoolduel.html"],
  ["Escape Road", "clescaperoad.html"],
  ["Escape Road 2", "clescaperoad-2.html"],
  ["Escape Road City 2", "clescaperoadcity2.html"],
  ["Evil Glitch", "clevilglitch.html"],
  ["Evolution", "clevolution.html"],
  ["Exoplanet Observation", "clexoobservation.html"],
  ["Extreme Run 3D", "clextremerun3d.html"],
  ["Fall Guys", "clfallguys.html"],
  ["Fears to Fathom: Home Alone", "clfearstofathomhomealone.html"],
  ["Fear Assessment (DEMO)", "clfearassessment.html"],
  ["Feed The Void", "clfeedthevoid.html"],
  ["Final Earth 2", "clfinalearth2.html"],
  ["Find The Alien", "clfindthealien.html"],
  ["Fireblob", "clfireblob.html"],
  ["Fireboy and Watergirl 2", "clfireboyandwatergirl2.html"],
  ["Fireboy and Watergirl 3", "clfireboyandwatergirl3.html"],
  ["Fish Eat Getting Big", "clfisheatgettingbig.html"],
  ["Fisquarium", "clfisquarium.html"],
  ["Five Nights at Candy's 1", "clfnac1.html"],
  ["Five Nights at Candy's 2", "clfnac2.html"],
  ["Five Nights at Baldis Redone", "clfivenightsatbaldisredone.html"],
  ["Five Nights at Epstein's", "clfivenightsatepsteins.html"],
  ["Five Nights at Winston's", "clfnaw.html"],
  ["Five Nights At Shrek's Hotel", "clfivenightsatshreks.html"],
  ["Flappy Dunk", "clflappydunk.html"],
  ["Fluidism", "clfluidism.html"],
  ["FNAF 2", "clFNAF2.html"],
  ["FNAF 3", "clFNAF3.html"],
  ["FNAF 4", "clFNAF4.html"],
  ["FNAF 4 Halloween", "clfnaf4halloween.html"],
  ["FNAF Pizzeria Simulator", "clfnafps.html"],
  ["FNAF Ultimate Custom Night", "clfnafucn.html"],
  ["FNAF Sister Location", "clfnafsl.html"],
  ["FNAF Shooter", "clfnafshooter.html"],
  ["FNAF World", "clfnafworldd.html"],
  ["FNAF 3 Remastered", "clfnaf3remastered.html"],
  ["Football Bros", "clfootballbros.html"],
  ["Football Legends", "clfootballlegends.html"],
  ["Folder Dungeon", "clfolderdungeon.html"],
  ["Fork n Sausage", "clforknsausage.html"],
  ["Fortzone Battle Royale", "clfortzone.html"],
  ["Freegemas", "clfreegemas.html"],
  ["From Rust To Ash", "clfromrusttoash.html"],
  ["Fused 240", "clfused240.html"],
  ["Funny Battle Simulator", "clfunnybattle.html"],
  ["Funny Battle Simulator 2", "clfunnybattle2.html"],
  ["Funny Mad Racing", "clfunnymadracing.html"],
  ["Funny Shooter 2", "clfunnyshooter22.html"]
];

const allGames = [...existingGames];

for (const [name, file] of newGamesData) {
  const id = name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '');
  if (!allGames.find(g => g.id === id)) {
    allGames.push({ id, name, file });
  }
}

fs.writeFileSync('./src/games.json', JSON.stringify(allGames, null, 2));
console.log(`Added ${newGamesData.length} games. Total games: ${allGames.length}`);
